### ISSUE TITLE
Creating Custom Input Parameters

### ISSUE THREAD

**Issue by ghbrjks** [AhmedSalih3d/SPHExample#18]
In your project, there are pre-generated particle layouts from DualSPHysics in .csv format located in the "input" folder. Could I learn how these were generated and how I can generate a .csv file with the same columns as in the project, specifically:
"Idp", "Vel:0", "Vel:1", "Vel:2", "Rhop", "Press", "Vor:0", "Vor:1", "Vor:2", "Type", "Points:0", "Points:1", "Points:2"

Currently, my .csv file contains only the following fields:
"Idp","Vel:0","Vel:1","Vel:2","Rhop","Type","Points:0","Points:1","Points:2"

I would greatly appreciate your help!

**Comment by AhmedSalih3d** [comment]
Hello @ghbrjks !

Yes of course. The format can vary slightly between each version of Paraview, but the basic principle is to use Paraview and open the .vtk files from DualSPHysics (or any other particle generation software) and then do the following:

![image](https://github.com/user-attachments/assets/60f6bcb3-703a-4d4e-8f71-d3014b098eb4)

Or open the spread sheet in Paraview, do crtl + a and copy into a text file and then deal with headers your self as far as I remember.

![image](https://github.com/user-attachments/assets/9847d56b-6b78-4d94-a3c5-b9762491720a)

If you make the format the same, then it should work well.

Just one note, I do not believe my code currently calculates vorticity, so it might be that those values will not work.

**Comment by ghbrjks** [comment]
![paraview_fIh4i3zdAh](https://github.com/user-attachments/assets/16b1f3b8-2ddb-4067-8338-ee8f6e6dd664)
![изображение](https://github.com/user-attachments/assets/12cf8aad-45cb-46ea-a371-54a8f2b702c2)
Yes, but the .vtk files created by DualSPHysics do not contain an array like "Press" (nor "Vor:0", etc., accordingly). I would like to understand how to include them there.

**Comment by AhmedSalih3d** [comment]
Oh, then you need to use DualSPHysics' post-processing scripts to be able to export the values you seek. Alternatively, you can also calculate the pressure using the same equation of state and the density with a calculation filter in Paraview. Then after you have post-processed and exported the initial conditions with all the values you mention, then you can do what I suggested above

**Comment by ghbrjks** [comment]
Okay, thanks!
