### ISSUE TITLE
Error wher try Pkg.add

### ISSUE THREAD

**Issue by PharmCat** [AhmedSalih3d/SPHExample#3]
When: 
```
Pkg.add(url="https://github.com/AhmedSalih3d/SPHExample.git")
```

```  
Activating new project at `C:\Users\vsarn\.julia\environments\SPHExample`

     Cloning git-repo `https://github.com/AhmedSalih3d/SPHExample.git`
    Updating git-repo `https://github.com/AhmedSalih3d/SPHExample.git`
ERROR: expected a `name` entry in project file at `C:\Users\vsarn\AppData\Local\Temp\jl_I7i58B\Project.toml`
```

**Comment by AhmedSalih3d** [comment]
Hello @PharmCat !

Thank you for reporting this, I have tested and confirmed. I got partly the way to the solution by renaming a file and adding name tag to Project.toml, but for some reason Revise.jl includet is not properly being used when installing the package the way you mention.. need some more time to dive into that sorry..

What worked for me was "git clone" directly, and then executing SPHExample.jl (previously MainSimulation.jl)

I also saw your second issue, will try to see if I can fix them in the weekend..

**Comment by AhmedSalih3d** [comment]
Hello @PharmCat !

I apologize for the long delay - thank you once again for opening the issue.

It has been resolved now and for me doing `Pkg.add(url="https://github.com/AhmedSalih3d/SPHExample.git")` works out of the box and the readme has been updated to match the new structure with the MainSimulation.jl being in an example folder now.

I got support nsajko on julia.discourse, thanks a lot, reference: https://discourse.julialang.org/t/my-package-cannot-be-installed-using-pkg-add/109294/7
